### ISSUE TITLE
Would it be useful if I added a seed option?

### ISSUE THREAD

**Issue by suspiciousfellow** [danibram/mocker-data-generator#104]
casual, faker, etc have seed options. There's not a documented way of doing that with this module. Is there one and if not if I added it and submitted a PR would you be likely to accept it?

**Comment by danibram** [comment]
Yes, sorry, i didnt have time to improve the library to be 100% modular, but if you want to add a generator, basically you can start reading the `src/lib/Generator.ts` there are the generators implemented, my next idea will be move the generators in separated files, but right now are there...

**Comment by marshallswain** [comment]
@danibram. Thanks for this awesome module! 

I'm interested in adding a simple `seed` method to the `Mocker` class, here: https://github.com/danibram/mocker-data-generator/blob/master/src/lib/Mocker.ts#L17

I would specifically like to be able to seed the internal database by using this api:

```js
mocker().seed(name, arrayOfData)
```

The `seed` method would accept a name and an array of data, like this:

```js
seed(name: string, data: []): Mocker {
  this.DB[name] = data
  return this
}
``` 

More complete example of usage:

```js
const mocker = require('mocker-data-generator').default

const assets = require('./assets.json')
const users = require('./services/users/users.fixtures')

mocker()
  .seed('assets', assets)
  .schema('users', users, 10)
  .build()
  .then(data => {
    debugger
  }, error => {
    debugger
  })

module.exports = { buildFixtures }
```

Do you foresee any issues with this API?  Would you be willing to merge a pull request if I submit one?

**Comment by danibram** [comment]
Hi!
Thanks for your comments! 
Yes, I have to admit that I misunderstood the issue at first, now its clear, and running in v2.8.0, sorry @suspiciousfellow
You can test [here](https://danibram.github.io/mocker-data-generator/#withSeed)
Thanks!
For the next one, PR always welcome, but today I was faster 😂

**Comment by danibram** [comment]
I think now we can close that issue

**Comment by marshallswain** [comment]
So awesome!  Thank you!
