### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ronakamlani** [danibram/mocker-data-generator#2]
Hello, I have tried most of library but I liked your own data generator..

Once I trying below code it gives me 'Cannot read property 'map' of undefined
' error.

Here is my code.

//At top header ..
var mocker    = require('mocker-data-generator/lib')
var util = require('util')
var faker     = require('faker')
var bcrypt = require('bcrypt');

var mongojs = require('mongojs');
var util = require('util');

//inside event.
var m = mocker()
    .schema('users', config.users, 3)
    .schema('users2', config.users, {uniqueField: 'email'})

    .schema('tags_helper', config.tags_helper,3)

    .schema('story', config.story, 5)
    .schema('story2', config.story, {uniqueField: 'title'})

    .build(function(data){
        console.log(util.inspect(data, {depth:10}))
   });

Error indicate near at .build.

Please, send me some solution..

**Comment by danibram** [comment]
Hi! First of all, thanks for report the issue, this will help to improve the module.
Can you pass me the models? Here or by email (info@dbr.io)
And also can you write me the node version?
I have tests for the module, in every compilation, so maybe its an error on the models. Can you put also a console log to know if config is accesible by the mocker code?

**Comment by ronakamlani** [comment]
Sure, now i have remove that code and move ahead with duplicate records, but I am sending you code and node.js version.

Thank you so much dude..
:)

**Comment by danibram** [comment]
I think after analyze the schemas that the are an external problem. Also i updated (v1.2.2) the module with a better catch of the errors, so now we can detect better if it is an issue of the module or external.
Thanks!

**Comment by ronakamlani** [comment]
Thank you so much for contribution. You saved my time..

Thanks..
:)
