### ISSUE TITLE
FakerJS posible Error

### ISSUE THREAD

**Issue by danibram** [danibram/mocker-data-generator#34]
@sleicht :

I get following warning:

`
WARNING in ./node_modules/faker/locale/ReadMe.md
Module parse failed: ./node_modules/faker/locale/ReadMe.md Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| # Read Me
|
| The files in this directory have been auto-generated from the `gulpfile`.
 @ ./node_modules/faker/locale ^\.\/.*$
 @ ./node_modules/mocker-data-generator/build/module/lib/Generator.js
 @ ./node_modules/mocker-data-generator/build/module/index.js
`

Is this only on my side or should this be fixed somehow?

**Comment by danibram** [comment]
Im checking and released a new version with a better loading of the locales packages of fakerJS, and i test all locales and i cant find any warning. If you provide me the model i can make a better check. 
Try this new version, maybe by error something is passing to the locale, now i check exactly the locales of fakerJS have.
Thank you

**Comment by sleicht** [comment]
Thanks for the fast fix. I use it in a AngularTS environment and the warning only comes while starting `ng serve`. Using the mocker works fine and without warning.

**Comment by danibram** [comment]
Ok, so i will close this. Thank you

**Comment by Indronil** [comment]
I am getting the same error and not a warning with angular 13 while running serve. Can somebody help me with it?
./node_modules/faker/locale/ReadMe.md:1:1 - Error: Module parse failed: Unexpected character ' ' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> # Read Me
| 
| The files in this directory have been auto-generated from the `gulpfile`.

I am using “mocker-data-generator” and I guess this library is a dependent on that. Is there a solution to get around it?
