### ISSUE TITLE
Help to Add examples to the playgroud

### ISSUE THREAD

**Issue by danibram** [danibram/mocker-data-generator#40]
Hello everyone!
I need some help to increase the number of examples in mocker, so these are the instructions:
- Go to the [playground](https://danibram.github.io/mocker-data-generator/)
- Create an example there, make sure that it is selfexplanatory and usefull for the rest of the users, the mission is to make accesible the use of this generator. Once is working and you make sure that is the best piece of code of your life... xD
- Fork the repo
- Go to `_docs_website/examples`
- Add a new file with the name of your example, please use shortest name you can. You can follow the other examples.
- Paste the code you used in the playground in this strcuture (You can use other examples to help you [this for example](https://github.com/danibram/mocker-data-generator/blob/master/_docs_website/examples/initial.js)). Easy, is something like this ->```module.exports = `YOUR CODE` ```
- Make a pull request and I will do the rest, the examples are autogenerated by a script so you dont need to touch in other files.

Thank you for contributing!!!

If you like the idea please star it and please make 1 pull per example in this way its more clear for me

PD: Of course involved by the spirit of the hackober fest you can make more pull request to improve the module, PR and issues are open to you

**Comment by terrance00** [comment]
Hi, I've created an example showcasing arrays.

Any other ideas you would need? Awesome library btw, started using it for component testing on angular. +1.

**Comment by danibram** [comment]
Closed because this will be rewrote with version 3
