### ISSUE TITLE
Fechas aleatorias formateadas

### ISSUE THREAD

**Issue by isaacdeveloper** [danibram/mocker-data-generator#7]
Hola, ¿se podría añadir una función que te devuelva una fecha aleatoria con el formato que se le pase por parámetros?

**Comment by danibram** [comment]
Perdona, se me paso contestarte. Al ser un agreagdor de librerias de terceros podriamos buscar una en la que puedas formatear las fechas, o sino sino te importa añadir una libreria mas podrias hacer algo como:

```
import {Datetime} from 'luxon'

/*...*/ en ttu modelo
function: function () {
    return DateTime.fromISO(this.faker.date.recent())
        .toLocaleString(DateTime.DATE_FULL)
}
```
 Y como eso con la libreria que quisieras, pero si, es una cosa a tener en cuenta.
Gracias!
