### ISSUE TITLE
Dynamically generated key

### ISSUE THREAD

**Issue by jdalrymple** [danibram/mocker-data-generator#74]
Would it be possible to generate the key as well as the value?

{
...
'chance.word' : ' chance.word'
...
}

**Comment by danibram** [comment]
Yes, its viable, i need to think better about how to do it. Thanks for the issue

**Comment by danibram** [comment]
I havent too much time and I priorized other features, sorry but this wont be implemented. If you want to contribute and add this feature, PRs always welcome! Thanks!
