### ISSUE TITLE
Nested Attribute support

### ISSUE THREAD

**Issue by faboulaws** [danibram/mocker-data-generator#87]
There is no example of nested attributes. For example, if I want to create a mock an entity with the structure below
```js
const article = {
    title: '...',
    seo: {
          title: "...",
          description: ""
    }
};
```

I need to create 2 entities

```js
const articleSchema = {
    title: {
        chance: 'word'
   },
  seo: {
        hasOne: 'seo'
 }
};

const seoSchema = {
     title: {
        chance: 'word'
     },
    description: {
        chance: 'word'
    },
};

mocker().schema('article',articleSchema, 1)
.schema('seo',seoSchema, 1)
```

Am I missing something or this is the best way to generate nested properties.

**Comment by danibram** [comment]
Hi,
You can use simply 1:

```
const articleSchema = {
    title: {
        chance: 'word'
    },
    seo: {
        title: {
            chance: 'word'
        },
        description: {
            chance: 'word'
        }
    }
};

mocker().schema('article',articleSchema, 1)
```
You can test [here the result](https://danibram.github.io/mocker-data-generator/), also you can use 2 entities if you need to share between more schemas.
Thanks for using mocker-data-generator!

**Comment by faboulaws** [comment]
Thanks for the quick response :-)
